<a href="https://colab.research.google.com/github/MrCherveN/Machine-Learning--4-0_HomeTasks/blob/main/HW7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
import numpy as np

In [2]:
my_arr = np.array([5, 15, 25, 35, 45])
print(my_arr)

zero_arr = np.zeros(7)
print(zero_arr)

one_arr = np.ones(6)
print(one_arr)

arange_arr = np.arange(10,20)
print(arange_arr)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [3]:
orig_arr = np.array([12, 24, 36, 48, 60])
print(f'Оригінальний Numpy-масив: {orig_arr}')

arr_mult = orig_arr * 2
print(f'Numpy-масив помножений на 2: {arr_mult}')

arr_add = orig_arr + 10
print(f'Numpy-масив збільшений на 10: {arr_add}')

arr_pow = orig_arr ** 2
print(f'Numpy-масив в степені 2: {arr_pow}')

arr_sqrt = np.sqrt(orig_arr).round(2)
print(f'Квадратний корінь з усіх елементів Numpy-масиву: {arr_sqrt}')

Оригінальний Numpy-масив: [12 24 36 48 60]
Numpy-масив помножений на 2: [ 24  48  72  96 120]
Numpy-масив збільшений на 10: [22 34 46 58 70]
Numpy-масив в степені 2: [ 144  576 1296 2304 3600]
Квадратний корінь з усіх елементів Numpy-масиву: [3.46 4.9  6.   6.93 7.75]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [4]:
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(data)

print(f'Середнє значення: {data.mean().round(2)}')
print(f'Мінімум: {data.min()}')
print(f'Максимум: {data.max()}')
print(f'Суму всіх елементів: {data.sum()}')

[18 27 33 41 52 68 79]
Середнє значення: 45.43
Мінімум: 18
Максимум: 79
Суму всіх елементів: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [5]:
arr = np.array([15, 22, 35, 44, 58, 67])
print(arr)

print(f'Перший елемент: {arr[0]}')
print(f'Останній елемент: {arr[-1]}')
print(f'Елементи з індексами 1 до 3: {arr[1:4]}')

mask = arr > 40
print(f'Елементи більші за 40: {arr[mask]}')


[15 22 35 44 58 67]
Перший елемент: 15
Останній елемент: 67
Елементи з індексами 1 до 3: [22 35 44]
Елементи більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [6]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [7]:
print(f'Виведіть форму (shape) матриці: {matrix.shape}')
print(f'Виведіть перший рядок: {matrix[0, :]}')
print(f'Виведіть другу колонку: {matrix[:, 1]}')
print(f'Обчисліть суму всіх елементів: {matrix.sum()}')
print(f'Обчисліть середнє всіх елементів: {matrix.mean()}')

Виведіть форму (shape) матриці: (3, 3)
Виведіть перший рядок: [2 4 6]
Виведіть другу колонку: [ 4 10 16]
Обчисліть суму всіх елементів: 90
Обчисліть середнє всіх елементів: 10.0
