<a href="https://colab.research.google.com/github/MrCherveN/Machine-Learning--4-0_HomeTasks/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import random


#random.seed(34)
#vector = np.array([random.uniform(0,1) for _ in range(1,10)])

np.random.seed(34)
vector = np.random.rand(10)

matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])

In [2]:
display(vector, matrix)

array([0.03856168, 0.78010046, 0.09270376, 0.63289269, 0.01389085,
       0.93615854, 0.42657438, 0.25308645, 0.18996531, 0.41482463])

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [3]:
vector.shape

(10,)

In [4]:
matrix.shape

(3, 3)

#
### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
# 1 --- тут вирішив, що потрібно зберегти нове значення в vector

vector = np.round(vector + 10, 2)
display(vector)
display(vector.shape)

array([10.04, 10.78, 10.09, 10.63, 10.01, 10.94, 10.43, 10.25, 10.19,
       10.41])

(10,)

In [6]:
# 2
matrix_2  = matrix * 2
display(matrix_2)

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [7]:
# 3
vector_pov2 = vector**2
display(vector_pov2)

array([100.8016, 116.2084, 101.8081, 112.9969, 100.2001, 119.6836,
       108.7849, 105.0625, 103.8361, 108.3681])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [9]:
# 1
result_matrix = np.dot(B, A)
display(result_matrix)
display(result_matrix.shape)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

In [10]:
# 2
display(np.dot(result_matrix, C))
display(np.dot(result_matrix, C).shape)

array([[0.5202],
       [0.2846]])

(2, 1)

In [11]:
# 3
display(np.dot(result_matrix, D))
display(np.dot(result_matrix, D).shape)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:
# 1
result_matrix_T = result_matrix.T
display(result_matrix_T)

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [13]:
# 2
vector_T = vector.T
display(vector_T)
display(vector_T.shape)

array([10.04, 10.78, 10.09, 10.63, 10.01, 10.94, 10.43, 10.25, 10.19,
       10.41])

(10,)

***Відповідь:***
- Змін не бачу, оскільки vector одновимірний масив і транспонування одновимірного масиву не змінює форму.

In [14]:
# 3
column_vector = np.expand_dims(vector, axis=1)
display(column_vector)
display(column_vector.shape)

array([[10.04],
       [10.78],
       [10.09],
       [10.63],
       [10.01],
       [10.94],
       [10.43],
       [10.25],
       [10.19],
       [10.41]])

(10, 1)

***Відповідь:***
- vector перетворився з одновимірного вектра-рядка в двовимірний вектор-стовпець.

In [15]:
# 4
column_vector_T = column_vector.T
display(column_vector_T)
display(column_vector_T.shape)

array([[10.04, 10.78, 10.09, 10.63, 10.01, 10.94, 10.43, 10.25, 10.19,
        10.41]])

(1, 10)